apiVersion: v1
kind: Service
metadata:
  name: tc2-hello-world-service
spec:
  type: LoadBalancer
  selector:
    app: tc2-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000